import Link from 'next/link'
import Image from 'next/image'
import Seo from '../components/layout/Seo'
// import styles from '../styles/Common.module.css'


export default function Home() {
  return (
    <div className=''>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Seo
        pageTitle={'official website'}
        pageDescription={'ページの概要文を記載します。'}
        pageImg={'https://demo.com'}
        pageImgWidth={1280}
        pageImgHeight={960}
        fontPath = {'https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap'}
      />

    </div>
  )
}
